# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_page_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
